//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HanumanInstitute.EngageBayApi.Properties {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("HanumanInstitute.EngageBayApi.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string ConfigAuthorizationRequired {
            get {
                return ResourceManager.GetString("ConfigAuthorizationRequired", resourceCulture);
            }
        }
        
        internal static string InvalidMethodForObjectType {
            get {
                return ResourceManager.GetString("InvalidMethodForObjectType", resourceCulture);
            }
        }
        
        internal static string ResponseInvalidJson {
            get {
                return ResourceManager.GetString("ResponseInvalidJson", resourceCulture);
            }
        }
        
        internal static string ObjectTypeMustBeSequence {
            get {
                return ResourceManager.GetString("ObjectTypeMustBeSequence", resourceCulture);
            }
        }
        
        internal static string ResponseErrorCode {
            get {
                return ResourceManager.GetString("ResponseErrorCode", resourceCulture);
            }
        }
        
        internal static string ResponseBadRequest {
            get {
                return ResourceManager.GetString("ResponseBadRequest", resourceCulture);
            }
        }
    }
}
